### ISSUE TITLE
Requesting value sets fails when CodeCounts are not present

### ISSUE THREAD

**Issue by rustyswayne** [HealthCatalyst/Fabric.Terminology#39]
In instances when code counts have not been triggered into the ValueSetCodeCountBASE table - requesting any value set (or collection containing such a value set) will fail.

**Comment by rustyswayne** [comment]
@j2jensen @corytak If/when these occur, I think we should add a `ValueSetCodeCount` object with an Empty Guid designating the CodeSystemGuid with a count of 0 or some negative number to indicate the counts were not available. 

Currently I am logging and throwing an exception.  However, since this prevents essentially an list query that may contain an offending value set and I think returning a value set with the "empty counts" is appropriate.  Further, it's likely that the codes could still be queried.

**Comment by j2jensen** [comment]
Under what conditions would this occur?

**Comment by rustyswayne** [comment]
In the new schema, when a ValueSet SAM is published a new table [ClientTerm].[ValueSetCodeCountBASE] is included which is _supposed_ to contain a collection of code counts per code system included in the value set.

Example: For the Diabetes ValueSet - 35F6B1A6-A72B-48F5-B319-F6CCAF15734D

ValueSetCodeCountBASE contains records for

ICD10CM Diagnosis - 302
ICD9CM Diagnosis - 54
SNOMED CT US Extension - 68

However, in the current publish there are four (4) valuesets that do not have any records in the code count tables.  I have a check in the repository that is currently throwing if it can't match the code counts as it is a required part of the result object: `ValueSetSummary`.

Killing the entire service over a data migration omission, in my opinion, makes the system overly brittle.  As I see it, there are three solutions:

1.   As described above, create a ValueSetCodeCount record that represents a missing data state and let the UI(s) handle the error.
2.  In instances when the error occurs, include a fallback query to count the codes per code system and return the full result.  
3. Same as 2, but also insert the results into the CodeSetCodeCount table to correct the data so that the issue does not happen again after memory cache expiration.

There is a big performance difference between the two options - first being fairly quick, whilst the second & third are potentially rather latent depending on how many value sets in the current query need to be fixed.  Also, even if we log the omissions (which we are) the second/third option may be deprioritized as a fix that needs resolution since the application corrects itself via query.

**Comment by ClintLing** [comment]
So I found the 4 value sets that have no entries.  They actually should have entries.  So my proposal is to do two things:  1) Fix these entries so that the data comes through.   2)  Change (filter) the data release so that you won't get any value sets that don't have entries.  I think that will fix the issue based on what you have described.  Does that sound okay?  Is having a value set with no entries something we even need or want to support?  I don't have a use case for it, a value set without an entry is useless.

My question is on the client authoring side.  If someone locally creates a value set without entries - will it crash the server? or is that not allowed?  Alternatively, if I change the count table to account for no entries it would have to have an entry for everything, i.e., every value set should have to have an entry for every possible coding system whether a zero or not - that would be the most logical fix to the table.  The other option of making a "dummy" coding system to indicate that something has no entries feels off.

**Comment by mikebuck** [comment]
I can’t think of a good reason for an empty valueset. I think we would prevent its creation.

Mike

**Comment by ClintLing** [comment]
I have fixed the aberrant value sets by adding the codes.  I have also locked the terminology release files so they cannot release a value set if it has no codes.  Let me know as our thought process develops on this.
