### ISSUE TITLE
StatusCD and additional Value Sets Filtering

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Terminology#53]
Should be able to filter value sets by version, source, and whether or not it's inactive/archived or active.

**Comment by rustyswayne** [comment]
@corytak Can you confirm we are on the same page with respect to the different statuses - active, inactive, archived.  It's my understanding that value set statuses could only be set for custom (ClientTerm) value sets and the published shared terminology value sets would always be active.

Also, since the client term value sets will be shared between applications, do you see any issues with status changes between apps?  Example MBL sets value set to inactive - so it's becomes inactive in PRB ...

**Comment by corytak** [comment]
@rustyswayne Right now we just have the concept of active/inactive.

However, I could definitely see the value in having more statuses (where is the Value Set in its content creation lifecycle): 
- Draft
- Under Review
- Published
- Archived (I see archived and inactive as the same thing) 

We may need some concept of write access beyond just saying isCustom.
- Locked
- Unlocked

In addition, we may need to define scope or read access on custom value sets:
- private: only seen by me 
- public: only seen by my organization
- public/published: seen by all organizations

These concepts do complicate things and I would love to have Cessily, Mike, and Maggie weigh in. I'm guessing we could start with just active/inactive as a first step and then add in some of these other concepts.

**Comment by rustyswayne** [comment]
@corytak @j2jensen I'm going to implement these as we discussed in our sit down last week.

Based on Cory's list 

- Draft
- Under Review
- Published
- Archived (I see archived and inactive as the same thing)

I am going to change **Published** to **Active** since Active is used by Shared Terminology and I don't see  any real difference.  

I'm also inclined to not implement **Under Review** at this time as we have not really defined any difference between it and the **Draft** status and we can add it later once we flesh out the permission concepts. 

- Draft -> Editable and only queryable when specifically requested by status.  Draft status may be changed to _**Active**_
- Active -> All fields EXCEPT Status are Read only.  Status may be changed to **_Archived_.** Value Sets with an Active status are the value sets generally used by the API queries.
- Archived -> All fields EXCEPT Status are Read only.  Status may be changed to **_Active_**. Only queryable when specifically requested by status. 

Note:  Once a status has been changed from _**Draft**_ to **Active** it may never be changed back.  It's essentially locked as discussed.  If a user wants to edit a value set that has already been marked **Active** (or **Archived** for that matter) a copy of the the value set would be created with the originGuid (parent) being populated with the originated ValueSetGuid to indicate that the new copy is based on the Active/Archived value set.   

A new value set, regardless of created from scratch or based on a copy of another value set will have a status of **Draft** (currently created as Active).  A second post will need to be made to update the status to **Active** / **Archive**.
