### ISSUE TITLE
Endpoint for csv of code values

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Terminology#54]
Need an endpoint for passing in a csv of code values that returns codes that are found and codes that are not found.

**Comment by rustyswayne** [comment]
@corytak Is this specifically for codes within a value set are do we also need a more generic endpoint for ALL codes regardless of code system or value set.  The latter may be odd in that `CodeCD`(s) are not unique across code systems.

What do you think about adding two endpoints:

      // For the /codes endpoint 
     public class CodesCsvMatchModel 
      {
           public IEnumerable<string> Codes { get; set; }

           public Guid CodeSystemGuid { get; set; } // we could do an array here as well
      }

      // For the /valuesetcodes endpoint
      public class ValueSetCodesCsvMatch
      {
            public IEnumerable<string> Codes { get; set; }

           public Guid ValueSetGuid { get; set; } // we could do an array here as well
       }


POST `/codes/csv`  

POST `/valuesetcodes/csv`

**Comment by corytak** [comment]
@rustyswayne It's for codes across all codesystems and valuesets. In the builder view somebody would upload a comma separated list of values and this endpoint would check to see if the code exists and return the appropriate view models for the codes found. 

There can be collisions across CodeCDs. We could force the user to specify the code set before trying to add the comma separated values to the right side of the builder?

**Comment by j2jensen** [comment]
> We could force the user to specify the code set before trying to add the comma separated values to the right side of the builder?

(Speaking without very much context) that seems like a good idea. A value set is supposed to be associated with a specific set of code systems. In PRB, the specific filter component is configured with specific code systems associated with it, so we know what to search for if they paste CSVs into the filter.

But you'd want to think of your specific use case and user experience. If it's common for a user to have a CSV and want to use it to generate a ValueSet without knowing what code sets are associated with it, maybe it'd be appropriate to return all the information for those codes and let the UI suggest Code Systems to add based on the info that comes back with those codes?

**Comment by corytak** [comment]
So thinking about an example. Somebody inputs CodeCD of 001. That corresponds to 13 records in the Code view. Most of those belong to MSDRG CodeSystems in different years. Another result is the ICD9 Diagnosis Code for Cholera and another result is the IDC10 Procedure Code for Central Nervous System and Cranial Nerves, Bypass. 

We can have a dropdown that lets a user choose which  CodeSystem but I imagine that would be an unpleasant experience if they had to choose MSDRG 2017 or MSDRG 2018 when a Codesystem called MSDRG is available and does not have that code in it. 

As part of the return value we could return the collisions as well ("The code entered has more than one match, which did you mean?") Across all codes 1961 have a counterpart in another code system so I would think this situation would be somewhat rare. I'd definitely be curious about Maggie and Mike's thoughts here.

**Comment by rustyswayne** [comment]
Looks like we should consider accommodating the most inclusive, across all code systems and allow duplicate CodeCD(s) in the result set.   I'll include an optional parameter for including an array of CodeSytemGuid(s) so that the consuming applications have a bit more granular controller over the results.

**Comment by rustyswayne** [comment]
@j2jensen This may be a good spot to have the flexibility to install a table managed outside the SAM as you envisioned.  I have the query working for multiple thousands of codes, but it is pretty latent do to the large number of codes in the Shared view paired with very large "IN LIST" (currently batching 500 codes per inlist query),  a good round number that seems to be comfortably around the timeout period - at least on DEV0002.

A query for ~4700 codes takes almost 3 minutes.

A possible better solution would be a  table we could insert the codes into a `BatchCodes` table with a Guid representing the batch - e.g. a record would be

- Guid BatchId
- string CodeCD

We would then do a join the BatchCodes table to the [Terminology].[Codes] table using the BatchId.  Once we have the results of the query, we would delete the BatchCodes by BatchId.

**Comment by j2jensen** [comment]
@rustyswayne Are you saying the table managed outside the SAM would be beneficial because you'd be able to add indexes to improve performance? Or would you envision some shape change that would make the query faster?

For the BatchCodes idea:
1. Can you check what the performance difference would be like?
2. I'd like to see a CreatedDTS field or something in there so that we can easily clean up orphaned data if we need to.

**Comment by rustyswayne** [comment]
@j2jensen Yes.  Similar to what we discussed for certain situations in the PB application with respect to excluding already selected values.

The workflow would be something like -

Count the number of _values_ that would be included in an **IN LIST**.  

If the _value_ is less than some number - say 500 - we would simply execute the SQL using the large IN constraint.  

If the _value_ is larger than 500, we would create a new BatchID (Guid.NewGuid()) and batch insert the values into the "BatchQuery" table with the BatchID associated with each record.  We then join the results table against the BatchQuery table (constrainted by the BatchID -> the guid) and get the results.  Once we have the results, we DELETE the BatchQuery table for the BatchID.  

I don't think we would need a CreatedDTS field as, in theory it will be empty unless being used.

I'll go ahead and get an example working for us to demo/review.

**Comment by rustyswayne** [comment]
@j2jensen The performance differences in the query execution time are pretty significant:

# IN LIST queries

Code sample size: **4,678**
IN LIST queries in Batches of 1500 items:
**System.Data.SqlClient.SqlException : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.**

Code sample size: **4,678**
IN LIST queries in **Batches of 500** items:
**Operation completed in 174.7046801 seconds.**

Code sample size: **4,678**
IN LIST queries in **Batches of 200** items
Operation completed in 175.3907576 seconds

Code sample size: **10**
IN LIST queries where Batch size is greater than sample size (e.g. 1 batch)
Operation completed in 4.6829431 seconds.

# BatchQuery JOIN

Code sample size: **4,678**
BatchQuery Join

- Attempt 1 - Operation completed in 10.4445924 seconds.
- Attempt 2 - Operation completed in 11.209843 seconds.
- Attempt 3 - Operation completed in 10.6689254 seconds.
- Attempt 4 - Operation completed in 10.4226492 seconds.

Code sample size: **10**

- Attempt 1 - Operation completed in 4.8355637 seconds.
- Attempt 2 - Operation completed in 4.6577049 seconds.
- Attempt 3 - Operation completed in 4.7149363 seconds.

**Comment by j2jensen** [comment]
@rustyswayne 

> I don't think we would need a CreatedDTS field as, in theory it will be empty unless being used.

Yeah, I was considering the exceptional, but possible, situation where the cleanup phase fails (network hiccup or something), leaving a chunk of data in here. It's not a huge deal, though.

> The performance differences in the query execution time are pretty significant

The key question with performance is "how fast is fast enough?" In this case, even the 10-code IN list takes 4 seconds, which I consider to be too slow for user interaction. If at all possible, we need to find a solution, or combination of solutions, that will take request times down to under 2 seconds, maximum. Would a database index do that? If not, would combining a database index and the batch table do it? If not, what other solutions should we look into?

**Comment by rustyswayne** [comment]
@j2jensen  I have not considered database indexes to this point as that would require the shared terminology team making changes and having a working prototype seemed to be the first step.  That being said, an index on the CodeCD column may help. @clintling what do you think?

> The key question with performance is "how fast is fast enough?" In this case, even the 10-code query takes 4 seconds, which I consider to be too slow for user interaction.

I completely agree with the assessment that 4 seconds is also too slow - and would actually go a step further and say that the API in general is too latent for "comfortable" user interaction.

## Addressing the latency issue:

### Refactor SQL Repositories to use lighter weight ORM
I was thinking of introducing a second version of the SQL repositories and using a lighter weight ORM like NPoco or Dapper.  I'll do this tomorrow (starting with one) the `SqlCodeSystemCodeRepository` and run the tests again for a comparison/evaluation.  

If the comparison proves that the alternative is significantly quicker,  I'll go ahead and write the Dapper/NPoco versions of the other repositories so that we can run the integration tests on both implementations.

### ElasticSearch
I have started looking at a solution (concept only at this point) that uses ElasticSearch indices.   This solution has proven to be a much quicker. In general response times under a second. However, the performance does drop when you start asking for larger page sizes albeit there is quite a bit that can be done by simply altering the models being indexed etc.  

I've been treating this branch as a concept that _seems_ to have legs but low priority and have really only been pecking at it to answer the "can I get this to work in ElasticSearch / NEST".

**Comment by j2jensen** [comment]
@rustyswayne Before bothering with Dapper, you can do a `.ToString()` on the Entity Framework query to see the SQL it produces, and test that SQL query directly against the database. It's possible that it's producing a suboptimal query, but I doubt that the framework itself is adding more than a couple dozen milliseconds to the query time. I'd only investigate another ORM if you determine that I'm wrong about that.

**Comment by rustyswayne** [comment]
@j2jensen Sure thing.  The status codes #53 revisions are taking a bit longer than I anticipated so I have had a chance to get back to this yet.
