### ISSUE TITLE
Error Messages not passing through

### ISSUE THREAD

**Issue by corytak** [HealthCatalyst/Fabric.Terminology#90]
This is user error on my part. Passing in an array of CodeOperations that had the same guid for add and remove. When I stepped through the code I got this error message from  `ValueSetModule.PatchValueSet() attemp.Exception`:
>Database operation expected to affect 1 row(s) but actually affected 2 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

Instead I got this back:
>{"code":"InternalServerError","message":"Failed to update a value set","target":"ValueSetApiModel","details":null,"innererror":null}

**Comment by rustyswayne** [comment]
Your use case illustrates that there needs to be some additional validation on the PATCH model and the API probably should have returned a **BadRequest** rather than an **InternalServerError** in this case with a message indicating you have duplicate keys.  I think it's OK to obfuscate the underlying database error to the API as long as it's logged by the service - server side.   @j2jensen two bits?

**Comment by j2jensen** [comment]
Yeah, I agree with what you just said, Rusty.

**Comment by rustyswayne** [comment]
This exact issue has been addressed - we have also made some additional refinements to error handling in Fabric.Populations.  These will be back ported to terminology if/when we do the WebApi refactoring.
